### ISSUE TITLE
Wrong Lambda2 criterion in macro folder

### ISSUE THREAD

**Issue by Lingle07** [Tecplot/handyscripts#4]
The macro for Lambda2 criterion is almost correct, except line 18 for s2o2_13.

It should be 
{s2o2_13} = {s11}*{s13} + {s12}*{s23} + {s13}*{s33} + {Omga12}*{Omga23},
instead of 
{s2o2_13} = {s11}*{s13} + {s12}*{s23} + {s13}*{s33} - {Omga12}*{Omga23}.

The minus sign usually came from the antisymmetric property of Omega. 
Therefore, matrix Omega*Omega (1,3) = Omega(1,2)*Omega(2,3), which does not involve minus sign. 
For cases like Omega*Omega (2,3) = Omega(2,1)*Omega(1,3) = - Omega(1,2)*Omega(1,3). We have minus sign here.

**Comment by Lingle07** [comment]
If you try some vortex that can be explicitly expressed, say, Rankine vortex, you should be able to find Eig1 not axisymmetric as expected.

**Comment by davetaflin** [comment]
Thanks, @Lingle07 I've made the change (finally... :-)
