### ISSUE TITLE
Doubts about TimeAverage.py

### ISSUE THREAD

**Issue by MerrylinStewart** [Tecplot/handyscripts#6]
Do i have to make any changes in the Time average script for "variables to be averaged" And "constant variables"? 

When I am running this script tecplot is crashing

**Comment by m-zaka** [comment]
what is the output on the python shell? any errors or warning?

**Comment by MerrylinStewart** [comment]
No.

**Comment by ScottFowler** [comment]
I'm unaware of any crash issues with this script.  Please contact the Tecplot support staff at support@tecplot.com.  We'll be happy to help diagnose the issue.

Regards,
Scott Fowler
Tecplot 360 Product Manager

**Comment by brandongit316** [comment]
@MerrylinStewart , have your tried running the script explicitly with specific variables to be averaged and/or constant variables ([see the example in the lines 42 and 43](https://github.com/Tecplot/handyscripts/blob/master/python/TimeAverage.py))?
    # Example:
    # variables_to_average = [dataset.variable("salinity"), dataset.variable("temp")]
    # constant_variables = [dataset.variable("x"), dataset.variable("y")]

**Comment by brandongit316** [comment]
@MerrylinStewart , I wanted to check-in. Did you find a workaround? Please let us know if not. If you have resolved the issue, I'll close this thread.

**Comment by RookieForgiveMe** [comment]
Actually I got the same question, do I have to change the code in TimeAverage.py such as variables_to_average and constant_varibles?
I think it should be changed into my own case but after I have changed these, I find the error "AttributeError: generator object has no attribute uid"

**Comment by RookieForgiveMe** [comment]
> 

Already fixed by reinstalling Python, guess the problem comes from the version of Python or maybe the path to the folder where the scripts are located. You'd better put all the scripts directly in the system disk (Personal opinion)

**Comment by brandongit316** [comment]
@RookieForgiveMe , those variables only need to be changed if you want a more performant script (averaging only the variables you care about). 
I also wanted to check-in, is the issue resolved for you? Feel free to email support@tecplot.com if you have any other specific questions in the future.

**Comment by RookieForgiveMe** [comment]
> @RookieForgiveMe , those variables only need to be changed if you want a more performant script (averaging only the variables you care about). I also wanted to check-in, is the issue resolved for you? Feel free to email [support@tecplot.com](mailto:support@tecplot.com) if you have any other specific questions in the future.
Thanks for your reply.
This issue is already sloved.
Thanks again.
