### ISSUE TITLE
issue with |MINVAR[nnn]|

### ISSUE THREAD

**Issue by lucad1299** [Tecplot/handyscripts#7]
Hey,
I'm having an issue with a macro similar to Convert_SolutionTime.mcr:

$!AlterData  [|current_zone|]
  Equation = '{Normal_temp} = {CoordinateX} / cos(0.919680578714)'
$!ActiveFieldMaps = [|current_zone|]
$!GETVARNUMBYNAME |temp_num|
  NAME = "Normal_temp"
$!AlterData  [|current_zone|]
  Equation = '{Normal_Coordinate} = {Normal_temp} - |MINVAR[|temp_num|]|'

The macro crashes with:

" >, <. >=, <=, &&, || ==, != are only allowed in first parameter of the IF() function.

If you are using '<' or '>' for MAX or MIN, please change this to use the MAX() or MIN() functions.

Example:
	Change {a}>{b} to MAX({a},{b})
	Change {a}<{b} to MIN({a},{b}).

Error occurred near position marked with "@" below:

@{Normal_Coordinate} = {Normal_temp} - |MINVAR[20]| "

So that leaves me with the question, why it correctly determines |temp_num| to be 20 but is unable to perform the equation. If i manually changed |temp_num| to 20 it works. Do I have to cast |temp_num| to some other sort of datatype? Also I don't have an IF statement in my macro so I don't get the crash message.

Convert_SolutionTime.mcr actually works in pretty much the same way but for him it seems to work?

Any help would be appreciated!

**Comment by brandongit316** [comment]
Hello @lucad1299, thank you for your question. A Tecplot 360 developer shares the following: 

The Tecplot macro language does not support nested variable evaluations (i.e. |’s) thus “|MINVAR[|temp_num|]|” is not possible.  There are a couple of work-arounds.

1. Use pytecplot instead
2. Use the “S” variable.

Option 2 is kind of sneaky and clunky but it works.

1. Activate all fieldmaps you want involved in the min calculation
2. Assign a “scatter sizing variable” (i.e. $!GlobalScatter Var = |temp_num|)
3. Use |MinS| in place of  |MINVAR[|temp_num|]| in your macro.

**Comment by lucad1299** [comment]
Thank you @brandon360plots !
That is indeed sneaky but yes it works! :)
