### ISSUE TITLE
How to Convert the Cell Centered Value To Node

### ISSUE THREAD

**Issue by raj-brown** [Tecplot/handyscripts#8]
Hi All-
Could you please help me converting the cell centered value to node points? I want to export x, y, z, and field from my plt data but my field is cell centered and x,y,z is nodal points. Could you please help me with script on PYTecplot.

Thanks!

**Comment by brandongit316** [comment]
Hi @raj-brown , does this KB article help?: https://kb.tecplot.com/2022/12/20/converting-variables-between-cell-centered-and-nodal/
